services:
  qui-ratio:
    build: .
    ports:
      - "8787:8787"
    environment:
      QUI_BASE_URL: "http://${QUI_IP}:7476"
      QUI_INSTANCE_ID: "1"
      QUI_API_KEY: "${QUI_API_KEY}"
      BUFFERS_PATH: "/data/buffers.yml"
      TRACKERS_PATH: "/data/trackers.yml"
    volumes:
      - ./buffers.yml:/data/buffers.yml:ro
      - ./trackers.yml:/data/trackers.yml:ro

